services:

    GtmPlugin\Resolver\ChannelFeatureResolver:
        arguments:
            - "@sylius.context.channel"
            - "%gtm.features%"
            - "%gtm.channels%"

    GtmPlugin\Twig\GtmChannelExtension:
        arguments:
            - "@GtmPlugin\\Resolver\\ChannelFeatureResolver"
        tags:
            - { name: twig.extension }

    GtmPlugin\EventListener\ChannelGtmListener:
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.channel"
            - "%gtm.channels%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
